# Дескриптивный анализ данных
```{r}
# Задание 1

setwd('/Users/kirillprivalov/Desktop/University/Year 1/Programming/cs102/homework06')

dataframe <- read.csv('music_genre.csv')

df <- dataframe[sample(nrow(dataframe), 20000),]

df <- df[!duplicated(df),]

df <- df[!(df$artist_name == 'empty_field'),]

print(df)
```
```{r}
# Задание 2
library(ggplot2)

# 2.1
genre_percentage <- table(df$music_genre) / length(df$music_genre) * 100
genre_percentage_df <- data.frame(Music_genre = names(genre_percentage), Percentage = genre_percentage)
print(genre_percentage_df)

# 2.2
genres <- names(table(df$music_genre))
values <- as.vector(table(df$music_genre))
df_genre_val <- data.frame(Music_genre = genres, Values = values)
cc <- ifelse(values < max(values), "grey", "red")
ggplot(df_genre_val, aes(x = Values, y = Music_genre, fill = Music_genre)) +
  geom_bar(stat = "identity") +
  scale_fill_hue(l = 40) +
  scale_x_continuous(limits = c(0, max(values) + 10)) +
  theme_minimal() +
  theme(panel.grid.major = element_line(colour = "gray"))

# 2.3
danceability_percentage <- select(df, c("music_genre", "danceability"))
danceable_genre <- danceability_percentage %>%
  group_by(music_genre) %>%
  summarise(danceability = mean(danceability)) %>%
  arrange(danceability) %>%
  tail(1) %>%
  ungroup() %>%
  select(-1)

# 2.4
genre_mode <- df %>%
  select(music_genre, mode) %>%
  count(music_genre, mode)
```
```{r}

```
```{r}
features <- df[, c("acousticness", "danceability", "duration_ms", "energy", "instrumentalness", "liveness", "loudness", "speechiness", "tempo", "valence", "popularity")] %>%
  select_if(~ !is.character(.))
features_corr_matrix <- cor(features)
heatmap(features_corr_matrix)

popularity_namelen <- df[, c("popularity", "track_name")]
popularity_namelen <- popularity_namelen[complete.cases(popularity_namelen), ]
popularity_namelen$track_name <- nchar(popularity_namelen$track_name)
popularity_namelen_corr <- cor(popularity_namelen)
print(popularity_namelen_corr)

```
